### ISSUE TITLE
Code license & copyright

### ISSUE THREAD

**Issue by clayadavis** [CambridgeUniversityPress/FirstCourseNetworkScience#1]
Should the code in this repo be [CC-BY](https://creativecommons.org/licenses/by/4.0/) or something like that?

Also, who owns the copyright for this code?

**Comment by filmenczer** [comment]
Nick wrote back: "[Authors] retain full copyright of the tutorial code on Github so you do not need to include Cambridge University Press in this. I think the license you mention [CC-BY-4.0] is fine if you are happy for it to be reused." 

License updated accordingly.
