### ISSUE TITLE
Chapter 0, Fig. 0.2, page 9: Colors represent film genres or languages/countries

### ISSUE THREAD

**Issue by giaruffo** [CambridgeUniversityPress/FirstCourseNetworkScience#15]
If nodes represent actors, as said in the caption and in the inline text, it does not make any sense to color nodes according the film genre, am I right? an actor may play different roles in different movies of differerent genres. Moreover colors match suspiciously too well with clusters: it looks like that colors have been assigned after the membership to a given modularity class. Just a guess.

**Comment by filmenczer** [comment]
You are right. The nodes are not colored by film genre. They are colored by communities, and then manual inspection reveals that the communities roughly correspond to film genres. This is explained in the text: 

> We also see that the networks are structured into several dense groups associated with periods, languages, or film genres: Hollywood (blue), Western (cyan), Mexican (purple), Chinese (yellow), Filipino (orange), Turkish and Eastern European (green), Indian (red), Greek (white), and adult (pink) stars in Figure 0.2(b). In Chapter 6 you will learn how to discover these groups and find out what they are about.
