### ISSUE TITLE
Chapter 0, Fig 0.4, Page 12. Caption: [...] The direction of the links is shown by arrows.

### ISSUE THREAD

**Issue by giaruffo** [CambridgeUniversityPress/FirstCourseNetworkScience#16]
Apparently there are no arrows in the picture.

**Comment by filmenczer** [comment]
Actually the arrows are there, but they are hard to see on the printed book. Here is a zoomed-in detail of the image:
![email](https://user-images.githubusercontent.com/10651090/74355462-e91c6800-4d8a-11ea-8a8c-b18fa3a149df.png)

**Comment by giaruffo** [comment]
oh, you are right, now I see them. Actually I am reading the electronic version the publisher sent me. If I zoom in, I can see arrows. Thank you
