### ISSUE TITLE
page 99 and Fig. 4.1: co-citation

### ISSUE THREAD

**Issue by giaruffo** [CambridgeUniversityPress/FirstCourseNetworkScience#18]
I could be wrong, but co-citing papers (connected with dashed blue links to the cited paper) should be both on the left of the target paper, if links points always backward in time.

**Comment by filmenczer** [comment]
[Co-citation](https://en.wikipedia.org/wiki/Co-citation) means two papers are both cited by one or more citing papers. In the figure, the citing papers are on the right, the cited papers are on the left. Co-cited papers (having a common citing paper) are connected by undirected co-citation links (dashed blue edges).
