### ISSUE TITLE
Question about Tutorial 7

### ISSUE THREAD

**Issue by filmenczer** [CambridgeUniversityPress/FirstCourseNetworkScience#8]
Is it possible to change the network (eg, rewire edges) in `state_transition()`? One would need to do that to implement the model in section 7.3.3 of the book...

**Comment by clayadavis** [comment]
Yes. Added a section illustrating it: https://github.com/CambridgeUniversityPress/FirstCourseNetworkScience/commit/19046c7e2351b0082f1773175f597b6703dfb247
