### ISSUE TITLE
Minimum version of NetworkX required?

### ISSUE THREAD

**Issue by filmenczer** [CambridgeUniversityPress/FirstCourseNetworkScience#9]
Should we require a minimum version of NetworkX in the tutorials? 

One exercise requires [greedy_modularity_communities](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.community.modularity_max.greedy_modularity_communities.html), which became available in v.2.2. 

Another exercise requires the version of [asyn_lpa_communities](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.community.label_propagation.asyn_lpa_communities.html) that we fixed, in the latest version (2.4).

**Comment by clayadavis** [comment]
Then the minimum should be 2.4.

**Comment by filmenczer** [comment]
Added a note about v2.4 in README.
